services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy-local
    restart: unless-stopped
    command: serve
    ports:
      - 127.0.0.1:8092:80
    environment:
      TZ: Europe/Samara
      NTFY_BASE_URL: http://127.0.0.1:8092
    volumes:
      - ntfy-cache:/var/lib/ntfy
      - ./etc:/etc/ntfy

volumes:
  ntfy-cache:
